"use client";

import { useState } from "react";
import { CurrencyField } from "@/components/form/currency-field";
import { DateField } from "@/components/form/date-field";
import { FormActions } from "@/components/form/form-actions";
import { FormField } from "@/components/form/form-field";
import { SelectField } from "@/components/form/select-field";
import { SectionCard } from "@/components/ui/section-card";
import { StatusAlert } from "@/components/ui/status-alert";
import { staffApi } from "@/lib/api-client";
import { STAFF_POSITIONS, type Option } from "@/lib/constants";
import type { FieldErrors, Staff } from "@/lib/types";
import { staffHireSchema, validate } from "@/lib/validation";

/** The nine inputs of Staff_hire_sp, in the order the instructor listed them. */
const EMPTY_FORM = {
  firstName: "",
  lastName: "",
  position: "",
  branchNo: "",
  dob: "",
  salary: "",
  telephone: "",
  mobile: "",
  email: "",
};

type Props = {
  branchOptions: Option[];
  branchesUnavailable: boolean;
  onHired: (staff: Staff) => void;
};

export function HireStaffForm({ branchOptions, branchesUnavailable, onHired }: Props) {
  const [values, setValues] = useState(EMPTY_FORM);
  const [errors, setErrors] = useState<FieldErrors>({});
  const [formError, setFormError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  function setField(field: keyof typeof EMPTY_FORM, value: string) {
    setValues((current) => ({ ...current, [field]: value }));
    setErrors((current) => {
      if (!(field in current)) return current;
      const next = { ...current };
      delete next[field];
      return next;
    });
  }

  function resetForm() {
    setValues(EMPTY_FORM);
    setErrors({});
    setFormError(null);
  }

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();

    // First pass: the shared schema, in the browser, for immediate feedback.
    const parsed = validate(staffHireSchema, values);
    if (!parsed.ok) {
      setErrors(parsed.fieldErrors);
      setFormError(parsed.message);
      return;
    }

    setErrors({});
    setFormError(null);
    setIsSubmitting(true);

    // Second pass happens on the server, which is the final authority.
    const result = await staffApi.hire(parsed.value);
    setIsSubmitting(false);

    if (!result.ok) {
      setErrors(result.fieldErrors ?? {});
      setFormError(result.message);
      return;
    }

    onHired(result.data);
    resetForm();
  }

  return (
    <SectionCard
      title="Hire a staff member"
      description="All nine inputs are passed to Staff_hire_sp. The staff number is generated by the database and returned in the response - it is never typed in here."
    >
      <form onSubmit={handleSubmit} noValidate>
        {formError ? (
          <div className="mb-5">
            <StatusAlert
              tone="error"
              title="The staff member was not hired"
              onDismiss={() => setFormError(null)}
            >
              {formError}
            </StatusAlert>
          </div>
        ) : null}

        {branchesUnavailable ? (
          <div className="mb-5">
            <StatusAlert tone="warning" title="Branch list unavailable">
              The branch numbers could not be loaded, so the branch box accepts a
              typed value. Check the connection status in the header.
            </StatusAlert>
          </div>
        ) : null}

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <FormField
            name="firstName"
            label="First name"
            required
            autoComplete="given-name"
            value={values.firstName}
            error={errors.firstName}
            onChange={(event) => setField("firstName", event.target.value)}
          />

          <FormField
            name="lastName"
            label="Last name"
            required
            autoComplete="family-name"
            value={values.lastName}
            error={errors.lastName}
            onChange={(event) => setField("lastName", event.target.value)}
          />

          <SelectField
            name="position"
            label="Position"
            required
            options={STAFF_POSITIONS}
            placeholder="Select a position"
            value={values.position}
            error={errors.position}
            onChange={(event) => setField("position", event.target.value)}
          />

          {branchesUnavailable ? (
            <FormField
              name="branchNo"
              label="Branch number"
              required
              hint="For example B003"
              value={values.branchNo}
              error={errors.branchNo}
              onChange={(event) => setField("branchNo", event.target.value)}
            />
          ) : (
            <SelectField
              name="branchNo"
              label="Branch number"
              required
              hint="Existing branches only - the staff row references DH_BRANCH"
              options={branchOptions}
              placeholder="Select a branch"
              value={values.branchNo}
              error={errors.branchNo}
              onChange={(event) => setField("branchNo", event.target.value)}
            />
          )}

          <DateField
            name="dob"
            label="Date of birth"
            required
            max={new Date().toISOString().slice(0, 10)}
            value={values.dob}
            error={errors.dob}
            onChange={(event) => setField("dob", event.target.value)}
          />

          <CurrencyField
            name="salary"
            label="Salary"
            required
            hint="Annual salary, digits only"
            value={values.salary}
            error={errors.salary}
            onChange={(event) => setField("salary", event.target.value)}
          />

          <FormField
            name="telephone"
            label="Telephone"
            type="tel"
            required
            autoComplete="tel"
            value={values.telephone}
            error={errors.telephone}
            onChange={(event) => setField("telephone", event.target.value)}
          />

          <FormField
            name="mobile"
            label="Mobile"
            type="tel"
            required
            value={values.mobile}
            error={errors.mobile}
            onChange={(event) => setField("mobile", event.target.value)}
          />

          <FormField
            name="email"
            label="Email"
            type="email"
            required
            autoComplete="email"
            value={values.email}
            error={errors.email}
            onChange={(event) => setField("email", event.target.value)}
          />
        </div>

        <FormActions
          submitLabel="Hire staff member"
          loadingLabel="Calling Staff_hire_sp..."
          isSubmitting={isSubmitting}
          onReset={resetForm}
        />
      </form>
    </SectionCard>
  );
}
