/**
 * Shared domain and transport types (deliverable P0-3).
 *
 * These types are the single contract between the browser, the server route
 * handlers, and the Oracle repository layer. Field names here are the JSON
 * names; the Oracle column names they map to are listed in
 * docs/api-contract.md so the UI and Oracle adapter bind to the same fields.
 */

/* ------------------------------------------------------------------ Staff */

/** A row of DH_STAFF as returned to the browser. */
export type Staff = {
  /** Generated by the documented STAFFNO generator - never edited. */
  staffNo: string;
  firstName: string;
  lastName: string;
  position: string;
  branchNo: string;
  /** ISO date, yyyy-mm-dd. Formatted for display only in the UI. */
  dob: string;
  salary: number;
  telephone: string;
  mobile: string;
  email: string;
};

/** The nine inputs accepted by Staff_hire_sp. STAFFNO is not one of them. */
export type StaffHireInput = Omit<Staff, "staffNo">;

/** Update allowlist for staff: salary, telephone and email only. */
export type StaffUpdateInput = Partial<
  Pick<Staff, "salary" | "telephone" | "email">
>;

/* ----------------------------------------------------------------- Branch */

/** A row of DH_BRANCH as returned to the browser. */
export type Branch = {
  /** Primary key - immutable once the branch exists. */
  branchNo: string;
  street: string;
  city: string;
  postcode: string;
};

/** Payload for new_branch. */
export type BranchCreateInput = Branch;

/** Update allowlist for branches: everything except BRANCHNO. */
export type BranchUpdateInput = Partial<
  Pick<Branch, "street" | "city" | "postcode">
>;

/** Result of the branch-address lookup: street plus city for one BRANCHNO. */
export type BranchAddress = Pick<Branch, "branchNo" | "street" | "city">;

/* ----------------------------------------------------------------- Client */

export type PropertyType = "House" | "Flat";

/** A row of DH_CLIENT as returned to the browser. */
export type Client = {
  /** Primary key - used only to locate the record, never updated. */
  clientNo: string;
  firstName: string;
  lastName: string;
  telephone: string;
  preferredPropertyType: PropertyType;
  maxRent: number;
};

export type ClientCreateInput = Omit<Client, "clientNo">;

/** Update allowlist for clients - any subset, but at least one field. */
export type ClientUpdateInput = Partial<Omit<Client, "clientNo">>;

/* -------------------------------------------------------------- Transport */

/** Field-level validation problems, keyed by the JSON field name. */
export type FieldErrors = Record<string, string>;

export type ApiSuccess<T> = {
  success: true;
  data: T;
};

export type ApiFailure = {
  success: false;
  error: {
    /** Safe, human-readable text. Never an Oracle stack trace. */
    message: string;
    /** Stable machine code, e.g. VALIDATION_ERROR, NOT_FOUND, DUPLICATE. */
    code: ApiErrorCode;
    fieldErrors?: FieldErrors;
  };
};

export type ApiEnvelope<T> = ApiSuccess<T> | ApiFailure;

export type ApiErrorCode =
  | "VALIDATION_ERROR"
  | "NOT_FOUND"
  | "DUPLICATE"
  | "DATABASE_ERROR"
  | "NETWORK_ERROR"
  | "SERVER_ERROR";

/** What every api-client call resolves to. Never throws for expected errors. */
export type ApiResult<T> =
  | { ok: true; data: T }
  | {
      ok: false;
      message: string;
      code: ApiErrorCode;
      fieldErrors?: FieldErrors;
      status: number;
    };

/** Payload of GET /api/health - drives the connection badge in the header. */
export type HealthStatus = {
  /** "oracle" for the live database, "mock" for offline demonstration. */
  dataSource: "oracle" | "mock";
  connected: boolean;
  /** Short description shown next to the badge, e.g. "DH_XXXX @ oracle-lab". */
  detail: string;
  checkedAt: string;
};
