import { getDataSource } from "@/lib/server/data-source";
import { created, fail, handleUnexpected, ok, readJson } from "@/lib/server/http";
import { staffHireSchema, validate } from "@/lib/validation";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/** GET /api/staff - every DH_STAFF row shown in the staff list. */
export async function GET() {
  try {
    const dataSource = await getDataSource();
    return ok(await dataSource.listStaff());
  } catch (error) {
    return handleUnexpected(error, "GET /api/staff");
  }
}

/**
 * POST /api/staff - the nine-input hire, executed through Staff_hire_sp.
 * STAFFNO is generated by the database side, never accepted from the browser.
 */
export async function POST(request: Request) {
  try {
    const parsed = validate(staffHireSchema, await readJson(request));
    if (!parsed.ok) {
      return fail("VALIDATION_ERROR", parsed.message, parsed.fieldErrors);
    }

    const dataSource = await getDataSource();
    return created(await dataSource.hireStaff(parsed.value));
  } catch (error) {
    return handleUnexpected(error, "POST /api/staff");
  }
}
