import type { Metadata } from "next";
import { PageHeader } from "@/components/layout/page-header";
import { StaffWorkspace } from "@/components/staff/staff-workspace";

export const metadata: Metadata = {
  title: "Staff",
  description: "Hire staff through Staff_hire_sp and maintain the allowed fields.",
};

export default function StaffPage() {
  return (
    <>
      <PageHeader
        title="Staff"
        description="Hire a staff member and maintain the records held in DH_STAFF. The staff number is generated by the database; salary, telephone and email are the only fields that can be changed afterwards."
        backedBy="DH_STAFF · Staff_hire_sp · POST /api/staff · PATCH /api/staff/[staffNo]"
      />
      <StaffWorkspace />
    </>
  );
}
